name: protoloom
channels:
  - conda-forge
dependencies:
  - python=3.11
  - protobuf
  - libprotobuf
  - openjdk=17
  - binutils
  - cxx-compiler
  - go=1.24
  - pkg-config
  - unzip
  - make
  - pip
  - pip:
      - -e .[dev]
